max_workers: ${CONCURRENCY:100}

DB_POOL_SIZE: ${DB_POOL_SIZE:20}
DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW:50}
DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT:120}

DB_URIS:
  "backend:Base": ${DB_URI:postgresql://${DB_USER:postgres}:${DB_PASSWORD:password}@${DB_SERVER:localhost}/${DB_NAME:backend}}

AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASS:guest}@${RABBIT_SERVER:localhost}:${RABBIT_PORT:5672}/${RABBIT_VHOST:}

JWT_SECRET: ${JWT_SECRET:super_secret}

WEB_SERVER_ADDRESS: ${SERVER_ADDRESS:0.0.0.0}:${SERVER_PORT:8000}

SENDGRID_KEY: ${SENDGRID_KEY:}

WEB_APP_ADDRESS: ${WEB_APP_ADDRESS:https://www.findfeatures.io}

STRIPE:
  API_KEY: ${STRIPE_PAYMENT_API_KEY:sk_test_bfLXLv5bBvHa3fJALYMPXh4M00YfZEL2Cz}

REDIS_URL: redis://${REDIS_SERVER:127.0.0.1}:${REDIS_PORT:6379}/${REDIS_DB:0}
