"""added stripe_sessions_completed and checkout_session_id to projects

Revision ID: b3af54251b82
Revises: ae9ea9766651
Create Date: 2020-01-03 16:02:56.393973

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b3af54251b82"
down_revision = "ae9ea9766651"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_sessions_completed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_datetime_utc",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "processing",
                "finished",
                "failed",
                name="stripesessioncompletedstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", name="stripe_sessions_completed_unique_event_id"
        ),
    )
    op.create_index(
        op.f("ixstripe_sessions_completed_event_id"),
        "stripe_sessions_completed",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stripe_sessions_completed_session_id"),
        "stripe_sessions_completed",
        ["session_id"],
        unique=False,
    )
    op.add_column(
        "projects", sa.Column("checkout_session_id", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "checkout_session_id")
    op.drop_index(
        op.f("ix_stripe_sessions_completed_session_id"),
        table_name="stripe_sessions_completed",
    )
    op.drop_index(
        op.f("ix_stripe_sessions_completed_event_id"),
        table_name="stripe_sessions_completed",
    )
    op.drop_table("stripe_sessions_completed")
    op.execute("DROP TYPE stripesessioncompletedstatusenum")
    # ### end Alembic commands ###
